//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Components;

namespace BlazorApp.Shared;

public partial class LifeCycle
{
    //[inject] private IConsole Console { get; set; } = default!;

    private string? _apiResponse;
    private List<string> _steps = new List<string>();
    private string? _var = "pas cliqué";


    protected override void OnInitialized()
    {
        _steps.Add(nameof(OnInitialized));
        Console.WriteLine("OnInitialed - DEBUT");
        base.OnInitialized();
        Console.WriteLine("OnInitialed - FIN");
    }

    protected override async Task OnInitializedAsync()
    {
        _steps.Add(nameof(OnInitializedAsync));
        Console.WriteLine("OnInitializedAsync - DEBUT");
        await base.OnInitializedAsync();

        //await Task.Delay(15000);
        _apiResponse = "Response blabla de l'API";

        Console.WriteLine("OnInitializedAsync - FIN");
    }

    protected override async Task OnParametersSetAsync()
    {
        _steps.Add(nameof(OnParametersSetAsync));
        Console.WriteLine("OnParametersSetAsync - DEBUT");
        await base.OnParametersSetAsync();
        Console.WriteLine("OnParametersSetAsync - FIN");
    }

    public override async Task SetParametersAsync(ParameterView parameters)
    {
        _steps.Add(nameof(SetParametersAsync));
        Console.WriteLine("SetParametersAsync - DEBUT");
        await base.SetParametersAsync(parameters);
        Console.WriteLine("SetParametersAsync - FIN");
    }

    protected override void OnAfterRender(bool firstRender)
    {

        _steps.Add(nameof(OnAfterRender));
        Console.WriteLine($"OnAfterRender - DEBUT (First ? {firstRender})");
        base.OnAfterRender(firstRender);
        Console.WriteLine($"OnAfterRender - FIN (First ? {firstRender}");
    }
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        _steps.Add(nameof(OnAfterRenderAsync));
        Console.WriteLine($"OnAfterRenderAsync - DEBUT (First ? {firstRender})");
        await base.OnAfterRenderAsync(firstRender);
        Console.WriteLine($"OnAfterRenderAsync - DEBUT (First ? {firstRender})");
    }

    protected override bool ShouldRender()
    {
        _steps.Add(nameof(ShouldRender));
        Console.WriteLine("ShouldRender - DEBUT");
        var result = base.ShouldRender();
        Console.WriteLine("ShouldRender - FIN");
        return result;
    }

}