//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using BlazorApp.Shared.Services;
using Microsoft.AspNetCore.Components;

namespace BlazorApp.Shared;


/*
 * public partial class LifeCycle : IDisposable - en version synchrone
 * public partial class LifeCycle : IAsyncDisposable - en version asynchrone
 * 
 */
public partial class LifeCycle : IAsyncDisposable
{
   

//[inject] private IConsole Console { get; set; } = default!;
[Inject] private IApiService ApiService { get; set; } = default!;

    private string? _apiResponse;
    private List<string> _steps = new List<string>();
    private string? _var = "pas cliqué";

    /// <summary>
    /// permet d'initialiser le composant de manière synchrone
    /// </summary>
    protected override void OnInitialized()
    {
        _steps.Add(nameof(OnInitialized));
        Console.WriteLine("OnInitialed - DEBUT");
        base.OnInitialized();
        Console.WriteLine("OnInitialed - FIN");
    }


    /// <summary>
    /// permet d'initialiser le composant de manière asynchrone
    /// </summary>
    /// <returns></returns>
    protected override async Task OnInitializedAsync()
    {
        _steps.Add(nameof(OnInitializedAsync));
        Console.WriteLine("OnInitializedAsync - DEBUT");
        await base.OnInitializedAsync();

        //await Task.Delay(15000);
        //_apiResponse = "Response blabla de l'API";

        Console.WriteLine("OnInitializedAsync - FIN");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    protected override async Task OnParametersSetAsync()
    {
        _steps.Add(nameof(OnParametersSetAsync));
        Console.WriteLine("OnParametersSetAsync - DEBUT");
        await base.OnParametersSetAsync();
        Console.WriteLine("OnParametersSetAsync - FIN");
    }

    /// <summary>
    /// encadre l'appel des paramètres passés au composant (le chef d'orchestre)
    /// </summary>
    /// <param name="parameters"></param>
    /// <returns></returns>
    public override async Task SetParametersAsync(ParameterView parameters)
    {
        _steps.Add(nameof(SetParametersAsync));
        Console.WriteLine("SetParametersAsync - DEBUT");
        await base.SetParametersAsync(parameters);
        Console.WriteLine("SetParametersAsync - FIN");
    }

    protected override void OnAfterRender(bool firstRender)
    {

        _steps.Add(nameof(OnAfterRender));
        Console.WriteLine($"OnAfterRender - DEBUT (First ? {firstRender})");
        base.OnAfterRender(firstRender);
        Console.WriteLine($"OnAfterRender - FIN (First ? {firstRender}");
    }

    /// <summary>
    /// méthode appelée après chaque rendu du composant 
    /// </summary>
    /// <param name="firstRender"></param>
    /// <returns></returns>
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        _steps.Add(nameof(OnAfterRenderAsync));
        Console.WriteLine($"OnAfterRenderAsync - DEBUT (First ? {firstRender})");

        if(firstRender)
        {
            //await Task.Delay(5000);// si l'api est un peu longue à répondre
            //_apiResponse = "Response blabla de l'API";
            _apiResponse = await ApiService.GetDataFromApi();
            //appel de StateHasChanged pour forcer le re-rendering du composant
            //peut aussi etre appelé dans OnInitialized pour un rendu initial mais résultat similaire
            StateHasChanged(); // mise à jour de l'UI après la modification de _apiResponse 

        }
        await base.OnAfterRenderAsync(firstRender);
        Console.WriteLine($"OnAfterRenderAsync - DEBUT (First ? {firstRender})");
    }

    /// <summary>
    /// permet de savoir si le composant doit être raffraichi ou pas
    /// </summary>
    /// <returns></returns>
    protected override bool ShouldRender()
    {
        _steps.Add(nameof(ShouldRender));
        Console.WriteLine("ShouldRender - DEBUT");
        var result = base.ShouldRender();
        Console.WriteLine("ShouldRender - FIN");
        return result;
    }

    public void Dispose()
    {
        System.Console.WriteLine("LifeCyle - Dispose");
    }

    public async ValueTask DisposeAsync()
    {
        System.Console.WriteLine("LifeCyle - Dispose async");
        await Task.Delay(5000);
    }

}